name: Flutter Community PR Validator

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate PR
        id: validation
        run: |
          VALID=true

          # --------------------
          # PR Title Validation
          # --------------------
          TITLE="${{ github.event.pull_request.title }}"

          if [[ ! "$TITLE" =~ ^(feature|fix|docs): ]]; then
            echo "Invalid title"
            VALID=false
          fi

          # --------------------
          # PR Description Validation
          # --------------------
          BODY="${{ github.event.pull_request.body }}"

          echo "$BODY" | grep -q "Feature Name:" || VALID=false
          echo "$BODY" | grep -q "Folder Name:" || VALID=false
          echo "$BODY" | grep -q "Purpose:" || VALID=false
          echo "$BODY" | grep -q "Dependencies:" || VALID=false
          echo "$BODY" | grep -q "Usage:" || VALID=false

          # --------------------
          # Folder Structure Validation
          # --------------------
          git fetch origin main

          CHANGED_FILES=$(git diff --name-only origin/main)

          INVALID=$(echo "$CHANGED_FILES" | grep -vE '^(api|utils|services|widgets|README.md)')

          if [ ! -z "$INVALID" ]; then
            echo "Invalid files found"
            VALID=false
          fi

          echo "valid=$VALID" >> $GITHUB_OUTPUT

      - name: Close Invalid PR
        if: steps.validation.outputs.valid == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}

          # Add Label
          gh pr edit $PR_NUMBER --add-label "invalid-structure"

          # Comment
          gh pr comment $PR_NUMBER --body "
          ❌ Pull Request rejected.

          Reason:
          - PR title format is invalid OR
          - Required PR template fields are missing OR
          - Folder structure does not follow repository standards.

          Required format:

          Title:
          feature: Dio Client

          Allowed folders:
          - api
          - utils
          - services
          - widgets

          Please fix the issues and create a new PR.
          "

          # Close PR
          gh pr close $PR_NUMBER

          exit 1

      - name: Auto Merge Valid PR
        if: steps.validation.outputs.valid == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge \
            ${{ github.event.pull_request.number }} \
            --squash \
            --auto